Mapillary_mapping_dict = {
    0: ' background',
    1: ' accident-area',
    2: ' both-directions',
    3: ' buses',
    4: ' chevron-left',
    5: ' chevron-left',
    6: ' chevron-left',
    7: ' chevron-left',
    8: ' chevron-left',
    9: ' chevron-right',
    10: ' chevron-right',
    11: ' chevron-right',
    12: ' chevron-right',
    13: ' chevron-right-unsure',
    14: ' distance',
    15: ' distance',
    16: ' distance',
    17: ' except-bicycles',
    18: ' extent-of-prohibition-area-both-direction',
    19: ' go-left',
    20: ' go-right',
    21: ' go-right',
    22: ' keep-left',
    23: ' keep-right',
    24: ' maximum-speed-limit-15',
    25: ' maximum-speed-limit-20',
    26: ' maximum-speed-limit-25',
    27: ' maximum-speed-limit-30',
    28: ' maximum-speed-limit-35',
    29: ' maximum-speed-limit-40',
    30: ' maximum-speed-limit-45',
    31: ' maximum-speed-limit-50',
    32: ' maximum-speed-limit-55',
    33: ' maximum-speed-limit-70',
    34: ' maximum-speed-limit-75',
    35: ' obstacle-delineator',
    36: ' obstacle-delineator',
    37: ' one-direction-left',
    38: ' one-direction-right',
    39: ' pass-right',
    40: ' priority-route-at-intersection',
    41: ' tow-away-zone',
    42: ' trucks',
    43: ' trucks-turn-right',
    44: ' turn-left',
    45: ' turn-right',
    46: ' airport',
    47: ' airport',
    48: ' bike-route',
    49: ' bus-stop',
    50: ' camp',
    51: ' central-lane',
    52: ' dead-end',
    53: ' dead-end-except-bicycles',
    54: ' disabled-persons',
    55: ' emergency-facility',
    56: ' end-of-built-up-area',
    57: ' end-of-limited-access-road',
    58: ' end-of-living-street',
    59: ' end-of-motorway',
    60: ' end-of-pedestrians-only',
    61: ' food',
    62: ' gas-station',
    63: ' highway-exit',
    64: ' hospital',
    65: ' interstate-route',
    66: ' limited-access-road',
    67: ' living-street',
    68: ' lodging',
    69: ' minimum-speed-40',
    70: ' motorway',
    71: ' no-parking',
    72: ' parking',
    73: ' parking',
    74: ' parking',
    75: ' parking',
    76: ' parking',
    77: ' parking',
    78: ' pedestrians-crossing',
    79: ' pedestrians-crossing',
    80: ' road-bump',
    81: ' safety-area',
    82: ' stairs',
    83: ' telephone',
    84: ' telephone',
    85: ' trailer-camping',
    86: ' other-sign',
    87: ' bicycles-only',
    88: ' bicycles-only',
    89: ' bicycles-only',
    90: ' buses-only',
    91: ' detour-left',
    92: ' do-not-block-intersection',
    93: ' do-not-stop-on-tracks',
    94: ' dual-lanes-go-straight-on-left',
    95: ' dual-lanes-go-straight-on-right',
    96: ' dual-lanes-turn-left-no-u-turn',
    97: ' dual-lanes-turn-left-or-straight',
    98: ' dual-lanes-turn-right-or-straight',
    99: ' dual-path-bicycles-and-pedestrians',
    100: ' dual-path-pedestrians-and-bicycles',
    101: ' end-of-bicycles-only',
    102: ' end-of-buses-only',
    103: ' end-of-maximum-speed-limit-30',
    104: ' end-of-maximum-speed-limit-70',
    105: ' end-of-maximum-speed-limit-70',
    106: ' end-of-no-parking',
    107: ' end-of-priority-road',
    108: ' end-of-prohibition',
    109: ' end-of-speed-limit-zone',
    110: ' give-way-to-oncoming-traffic',
    111: ' go-straight',
    112: ' go-straight',
    113: ' go-straight-or-turn-left',
    114: ' go-straight-or-turn-left',
    115: ' go-straight-or-turn-left',
    116: ' go-straight-or-turn-right',
    117: ' go-straight-or-turn-right',
    118: ' height-limit',
    119: ' keep-left',
    120: ' keep-left',
    121: ' keep-right',
    122: ' keep-right',
    123: ' keep-right',
    124: ' keep-right',
    125: ' lane-control',
    126: ' left-turn-yield-on-green',
    127: ' maximum-speed-limit-10',
    128: ' maximum-speed-limit-100',
    129: ' maximum-speed-limit-100',
    130: ' maximum-speed-limit-110',
    131: ' maximum-speed-limit-120',
    132: ' maximum-speed-limit-15',
    133: ' maximum-speed-limit-20',
    134: ' maximum-speed-limit-25',
    135: ' maximum-speed-limit-25',
    136: ' maximum-speed-limit-30',
    137: ' maximum-speed-limit-30',
    138: ' maximum-speed-limit-35',
    139: ' maximum-speed-limit-40',
    140: ' maximum-speed-limit-40',
    141: ' maximum-speed-limit-40',
    142: ' maximum-speed-limit-45',
    143: ' maximum-speed-limit-45',
    144: ' maximum-speed-limit-5',
    145: ' maximum-speed-limit-50',
    146: ' maximum-speed-limit-50',
    147: ' maximum-speed-limit-55',
    148: ' maximum-speed-limit-60',
    149: ' maximum-speed-limit-65',
    150: ' maximum-speed-limit-70',
    151: ' maximum-speed-limit-80',
    152: ' maximum-speed-limit-90',
    153: ' maximum-speed-limit-led-100',
    154: ' maximum-speed-limit-led-60',
    155: ' maximum-speed-limit-led-80',
    156: ' minimum-safe-distance',
    157: ' mopeds-and-bicycles-only',
    158: ' no-bicycles',
    159: ' no-bicycles',
    160: ' no-bicycles',
    161: ' no-buses',
    162: ' no-entry',
    163: ' no-hawkers',
    164: ' no-heavy-goods-vehicles',
    165: ' no-heavy-goods-vehicles',
    166: ' no-heavy-goods-vehicles',
    167: ' no-heavy-goods-vehicles',
    168: ' no-heavy-goods-vehicles-or-buses',
    169: ' no-left-turn',
    170: ' no-left-turn',
    171: ' no-left-turn',
    172: ' no-mopeds-or-bicycles',
    173: ' no-motor-vehicle-trailers',
    174: ' no-motor-vehicles',
    175: ' no-motor-vehicles',
    176: ' no-motor-vehicles-except-motorcycles',
    177: ' no-motor-vehicles-except-motorcycles',
    178: ' no-motorcycles',
    179: ' no-motorcycles',
    180: ' no-overtaking',
    181: ' no-overtaking',
    182: ' no-overtaking',
    183: ' no-overtaking',
    184: ' no-overtaking-by-heavy-goods-vehicles',
    185: ' no-parking',
    186: ' no-parking',
    187: ' no-parking',
    188: ' no-parking-or-no-stopping',
    189: ' no-parking-or-no-stopping',
    190: ' no-parking-or-no-stopping',
    191: ' no-pedestrians',
    192: ' no-pedestrians',
    193: ' no-pedestrians',
    194: ' no-pedestrians-or-bicycles',
    195: ' no-right-turn',
    196: ' no-right-turn',
    197: ' no-right-turn',
    198: ' no-stopping',
    199: ' no-stopping',
    200: ' no-stopping',
    201: ' no-stopping',
    202: ' no-stopping',
    203: ' no-straight-through',
    204: ' no-straight-through',
    205: ' no-turn-on-red',
    206: ' no-turn-on-red',
    207: ' no-turn-on-red',
    208: ' no-turns',
    209: ' no-u-turn',
    210: ' no-u-turn',
    211: ' no-u-turn',
    212: ' no-vehicles-carrying-dangerous-goods',
    213: ' one-way-left',
    214: ' one-way-left',
    215: ' one-way-left',
    216: ' one-way-right',
    217: ' one-way-right',
    218: ' one-way-right',
    219: ' one-way-straight',
    220: ' parking-restrictions',
    221: ' pass-on-either-side',
    222: ' pass-on-either-side',
    223: ' passing-lane-ahead',
    224: ' pedestrians-only',
    225: ' pedestrians-only',
    226: ' priority-over-oncoming-vehicles',
    227: ' priority-road',
    228: ' radar-enforced',
    229: ' reversible-lanes',
    230: ' road-closed',
    231: ' road-closed',
    232: ' road-closed-to-vehicles',
    233: ' road-closed-to-vehicles',
    234: ' roundabout',
    235: ' roundabout',
    236: ' shared-path-bicycles-and-pedestrians',
    237: ' shared-path-pedestrians-and-bicycles',
    238: ' stop',
    239: ' stop',
    240: ' stop',
    241: ' stop-here-on-red-or-flashing-light',
    242: ' stop-here-on-red-or-flashing-light',
    243: ' stop-signals',
    244: ' text-four-lines',
    245: ' triple-lanes-turn-left-center-lane',
    246: ' truck-speed-limit-60',
    247: ' turn-left',
    248: ' turn-left',
    249: ' turn-left',
    250: ' turn-left-ahead',
    251: ' turn-right',
    252: ' turn-right',
    253: ' turn-right',
    254: ' turn-right-ahead',
    255: ' turn-right-ahead',
    256: ' turning-vehicles-yield-to-pedestrians',
    257: ' u-turn',
    258: ' weight-limit',
    259: ' weight-limit-with-trucks',
    260: ' width-limit',
    261: ' wrong-way',
    262: ' yield',
    263: ' accidental-area-unsure',
    264: ' added-lane-right',
    265: ' bicycles-crossing',
    266: ' bicycles-crossing',
    267: ' bicycles-crossing',
    268: ' bus-stop-ahead',
    269: ' children',
    270: ' children',
    271: ' crossroads',
    272: ' crossroads',
    273: ' crossroads-with-priority-to-the-right',
    274: ' curve-left',
    275: ' curve-left',
    276: ' curve-right',
    277: ' curve-right',
    278: ' dip',
    279: ' divided-highway-ends',
    280: ' divided-highway-ends',
    281: ' domestic-animals',
    282: ' domestic-animals',
    283: ' double-curve-first-left',
    284: ' double-curve-first-left',
    285: ' double-curve-first-right',
    286: ' double-curve-first-right',
    287: ' double-reverse-curve-right',
    288: ' double-turn-first-right',
    289: ' dual-lanes-right-turn-or-go-straight',
    290: ' emergency-vehicles',
    291: ' equestrians-crossing',
    292: ' falling-rocks-or-debris-right',
    293: ' falling-rocks-or-debris-right',
    294: ' falling-rocks-or-debris-right',
    295: ' flaggers-in-road',
    296: ' hairpin-curve-left',
    297: ' hairpin-curve-left',
    298: ' hairpin-curve-right',
    299: ' hairpin-curve-right',
    300: ' height-restriction',
    301: ' horizontal-alignment-left',
    302: ' horizontal-alignment-right',
    303: ' horizontal-alignment-right',
    304: ' junction-with-a-side-road-acute-left',
    305: ' junction-with-a-side-road-acute-right',
    306: ' junction-with-a-side-road-perpendicular-left',
    307: ' junction-with-a-side-road-perpendicular-left',
    308: ' junction-with-a-side-road-perpendicular-left',
    309: ' junction-with-a-side-road-perpendicular-right',
    310: ' junction-with-a-side-road-perpendicular-right',
    311: ' kangaloo-crossing',
    312: ' loop-270-degree',
    313: ' narrow-bridge',
    314: ' narrow-bridge',
    315: ' offset-roads',
    316: ' other-danger',
    317: ' other-danger',
    318: ' pass-left-or-right',
    319: ' pass-left-or-right',
    320: ' pedestrian-stumble-train',
    321: ' pedestrians-crossing',
    322: ' pedestrians-crossing',
    323: ' pedestrians-crossing',
    324: ' pedestrians-crossing',
    325: ' pedestrians-crossing',
    326: ' pedestrians-crossing',
    327: ' pedestrians-crossing',
    328: ' playground',
    329: ' playground',
    330: ' railroad-crossing',
    331: ' railroad-crossing',
    332: ' railroad-crossing',
    333: ' railroad-crossing-with-barriers',
    334: ' railroad-crossing-with-barriers',
    335: ' railroad-crossing-with-barriers',
    336: ' railroad-crossing-without-barriers',
    337: ' railroad-crossing-without-barriers',
    338: ' railroad-crossing-without-barriers',
    339: ' railroad-intersection',
    340: ' railroad-intersection',
    341: ' restricted-zone',
    342: ' road-bump',
    343: ' road-bump',
    344: ' road-narrows',
    345: ' road-narrows',
    346: ' road-narrows-left',
    347: ' road-narrows-left',
    348: ' road-narrows-right',
    349: ' road-narrows-right',
    350: ' road-widens',
    351: ' road-widens-right',
    352: ' roadworks',
    353: ' roadworks',
    354: ' roadworks',
    355: ' roadworks',
    356: ' roundabout',
    357: ' roundabout',
    358: ' school-zone',
    359: ' shared-lane-motorcycles-bicycles',
    360: ' slippery-motorcycles',
    361: ' slippery-road-surface',
    362: ' slippery-road-surface',
    363: ' steep-ascent',
    364: ' stop-ahead',
    365: ' t-roads',
    366: ' t-roads',
    367: ' texts',
    368: ' texts',
    369: ' texts',
    370: ' traffic-merges-left',
    371: ' traffic-merges-left',
    372: ' traffic-merges-right',
    373: ' traffic-merges-right',
    374: ' traffic-signals',
    375: ' traffic-signals',
    376: ' traffic-signals',
    377: ' traffic-signals',
    378: ' trail-crossing',
    379: ' trams-crossing',
    380: ' trucks-crossing',
    381: ' turn-left',
    382: ' turn-right',
    383: ' turn-right',
    384: ' two-way-traffic',
    385: ' two-way-traffic',
    386: ' uneven-road',
    387: ' uneven-road',
    388: ' uneven-roads-ahead',
    389: ' wild-animals',
    390: ' wild-animals',
    391: ' winding-road-first-left',
    392: ' winding-road-first-left',
    393: ' winding-road-first-right',
    394: ' winding-road-first-right',
    395: ' wombat-crossing',
    396: ' y-roads'
}

GTSDB_mapping_dict = {
    0 :" speed limit 20 (prohibitory)",
    1 :" speed limit 30 (prohibitory)",
    2 :" speed limit 50 (prohibitory)",
    3 :" speed limit 60 (prohibitory)", 
    4 :" speed limit 70 (prohibitory)",
    5 :" speed limit 80 (prohibitory)",
    6 :" restriction ends 80 (other)",
    7 :" speed limit 100 (prohibitory)",
    8 :" speed limit 120 (prohibitory)",
    9 :" no overtaking (prohibitory)",
    10 :" no overtaking (trucks) (prohibitory)",
    11 :" priority at next intersection (danger)",
    12 :" priority road (other)",
    13 :" give way (other)",
    14 :" stop (other)",
    15 :" no traffic both ways (prohibitory)",
    16 :" no trucks (prohibitory)",
    17 :" no entry (other)",
    18 :" danger (danger)",
    19 :" bend left (danger)",
    20 :" bend right (danger)",
    21 :" bend (danger)",
    22 :" uneven road (danger)",
    23 :" slippery road (danger)",
    24 :" road narrows (danger)",
    25 :" construction (danger)",
    26 :" traffic signal (danger)",
    27 :" pedestrian crossing (danger)",
    28 :" school crossing (danger)",
    29 :" cycles crossing (danger)",
    30 :" snow (danger)",
    31 :" animals (danger)",
    32 :" restriction ends (other)",
    33 :" go right (mandatory)",
    34 :" go left (mandatory)",
    35 :" go straight (mandatory)",
    36 :" go right or straight (mandatory)",
    37 :" go left or straight (mandatory)",
    38 :" keep right (mandatory)",
    39 :" keep left (mandatory)",
    40 :" roundabout (mandatory)",
    41 :" restriction ends (overtaking) (other)",
    42 :" restriction ends (overtaking (trucks)) (other)",
        }
